### ISSUE TITLE
把 Taro.getCurrentPages() 放在 useEffect里执行，如果有多个副作用，不好控制顺序哦

### ISSUE THREAD

**Issue by briefguo** [zephyrpersonal/taro-router-hook#1]
![image](https://user-images.githubusercontent.com/9976575/61621918-5ad57d00-aca6-11e9-9278-c1d43618edd6.png)
![image](https://user-images.githubusercontent.com/9976575/61621946-6de84d00-aca6-11e9-9966-acc4caf576b9.png)

比如这时候，我想用router.query去开启新的异步的时候，理想情况应该是先拿到query后，发异步请求。Taro.getCurrentPages是直接可以执行的方法哦，并不需要放在useEffect里才可以

**Comment by zephyrpersonal** [comment]
hi，感谢关注这个小项目。

Taro.getCurrentPages的确是一个同步方法，但他却不能保证在 Page/组件 初始化时就能获取到正确的路由栈。所以才使用了在useEffect里异步获取（当然由于没有完备的测试，可能里面还有别的问题，但至少在我们现有的小程序项目里，如期运作）

这个问题和Taro的组件初始化机制有关。在他们的文档中有一些体现。

https://taro-docs.jd.com/taro/docs/best-practice.html#%E5%B0%8F%E7%A8%8B%E5%BA%8F%E4%B8%AD%E9%A1%B5%E9%9D%A2%E7%94%9F%E5%91%BD%E5%91%A8%E6%9C%9F-componentwillmount-%E4%B8%8D%E4%B8%80%E8%87%B4%E9%97%AE%E9%A2%98

实质上在class组件内也需要在willmount的生命周期里才能正确拿到taro-router的param，具体的源码没有翻过，我猜测应该也是组件attach前置导致的时序错乱。

不知是否解答了您的疑惑。

我们也在项目中全面推进函数式组件和hooks，有采坑经验和心得也希望多多交流。

**Comment by zephyrpersonal** [comment]
@briefguo 顺便，我们内部的最佳实践简化一下就是

```js
export default function DetailPage(){
    const [{query}] = useRouter()
    if(!query) return null
    return <View>xxx</View>
}
```

**Comment by zephyrpersonal** [comment]
我们内部是有一个hook用来获取远程数据的，其中有参数可以控制是否自动发起请求，渲染层也有对应的Boundry通过返回的结果进行条件渲染。其实大可不必追求“顺序“，更多关注于组件的状态。

**Comment by briefguo** [comment]
Hi @zephyrpersonal .

感谢你的耐心回答，感谢你的项目给了我思路。我也是想试着 All in hooks 会不会有啥共性的代码能够提取出来，所以通过关键字搜到了你的项目。

> 其实大可不必追求“顺序“，更多关注于组件的状态。

你说的这个，适合响应式的思路。说实话，hooks确实如你所说的那样，不用过多关注它的顺序。不过我觉得：对于程序阅读来说，**顺序描述**才是对逻辑的正当描述。

**Comment by zephyrpersonal** [comment]
Hi @briefguo，不好意思由于长时间没有反馈上午把issue close了。

我觉得可能我没有很好地表述让你误解了。

首先这个hook“那么难用”完全是因为我们在taro的环境里做的妥协...
为了达成这种妥协，我们用了一些额外的状态标记位来描述我们组件的状态，这个本身我也是反感的（但同时我们又不得不all-in-hooks来抹平各个平台开发的体验。）。在我们试图迁移小程序生命周期至hook的过程中感觉坑就更深了，所以我也在README里添加了caution提示希望看到这个库的同行们有一个心理预期，斟酌是否能够应用到自己的架构里。

其次关于顺序我其实更多的是在讲异步请求等副作用。从可读性上来讲我认同顺序描述一定是最符合人类直觉的。但由于前端开发存在太多的副作用，关注状态有时候会比关注过程更加可预测，就好比使用redux的时候不会在组件里 await 一个 action 吧，这个我相信我们应该能够达成共识的。

**Comment by briefguo** [comment]
嗯，了解了。

非常感谢，希望有更多关于开发上的交流。
